
[#tileformats-tile-formats]
= Tile Formats

The link:../README.md#tile-content[tile content] in a 3D Tiles tileset represents the renderable content of a tile. It is referred to with the `content.uri` of the tile JSON.

The primary tile format in 3D Tiles 1.1 is the link:glTF/[glTF Tile Format]. It is built on https://github.com/KhronosGroup/glTF[glTF 2.0] and allows modeling many different use cases and different forms of renderable content in 3D Tiles.

[#tileformats-legacy-tile-formats]
== Legacy Tile Formats

The following tile formats have been part of 3D Tiles 1.0, and have been superseded by the See xref:TileFormats/glTF/README.adoc#tileformats-gltf-gltf[glTF Tile Format].

|===
| Legacy Format | Uses

| xref:TileFormats/Batched3DModel/README.adoc#tileformats-batched3dmodel-batched-3d-model[Batched 3D Model (`b3dm`)] 
| Heterogeneous 3D models

| xref:TileFormats/Instanced3DModel/README.adoc#tileformats-instanced3dmodel-instanced-3d-model[Instanced 3D Model (`i3dm`)]
| 3D model instances

| xref:TileFormats/PointCloud/README.adoc#tileformats-pointcloud-point-cloud[Point Cloud (`pnts`)]
| Massive number of points

| xref:TileFormats/Composite/README.adoc#tileformats-composite-composite[Composite (`cmpt`)]
| Concatenate tiles of different formats into one tile
|===

See the See xref:TileFormats/glTF/README.adoc#tileformats-gltf-appendix-a-migration-from-legacy-tile-formats[migration guide]. for further information about how these use cases can be modeled based on the glTF tile format.
