
[#metadata-referenceimplementation-schema-schema-implementation]
= Schema Implementation

// Definitions of the directory structure to ensure that relative
// links between ADOC files in sibling directories can be resolved.
ifdef::env-github[]
:url-specification: ../../../
:url-specification-metadata: {url-specification}Metadata/
endif::[]
ifndef::env-github[]
:url-specification:
:url-specification-metadata:
endif::[]

The xref:{url-specification-metadata}README.adoc#metadata-3d-metadata-specification[3D Metadata Specification] defines xref:{url-specification-metadata}README.adoc#metadata-schemas[schemas] as a description of the structure of metadata, consisting of classes with different properties, and enum types. The following is the description of a JSON-based representation of such a schema and its elements. It is used as the basis for defining the metadata structure in the following implementations:

* xref:{url-specification-implicittiling}README.adoc#implicittiling-implicit-tiling[3D Tiles Metadata Implicit Tilesets] - Assigns metadata to tilesets, tiles, groups, and contents in a 3D Tiles tileset. A property table is defined for subtrees of an implicit tile hierarchy, and stores metadata that is associated with the nodes of such a subtree.
* https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_structural_metadata[`EXT_structural_metadata`] -- Assigns metadata to vertices, texels, and features in a glTF asset. A property table is defined in the top-level extension object. The property values are stored in standard glTF buffer views.

The full JSON schema definition for this implementation can be found in link:https://github.com/CesiumGS/3d-tiles/tree/main/specification/schema/Schema/[the Schema directory of the specification].

[#metadata-referenceimplementation-schema-schema]
== Schema

_Defined in 
ifdef::env-github[]
link:https://github.com/CesiumGS/3d-tiles/tree/main/specification/schema/Schema/schema.schema.json[`schema.schema.json`]._
endif::[]
ifndef::env-github[]
<<reference-schema-schema,`schema.schema.json`>>._
endif::[]

A schema defines a set of classes and enums. Classes serve as templates for entities. They provide a list of properties and the type information for those properties. Enums define the allowable values for enum properties.

[NOTE]
.Example
====
Schema with a `tree` class, and a `speciesEnum` enum that defines different species of trees. Later examples show how these structures in more detail.

[%unnumbered]
[source,jsonc]
----
{
  "schema": {
    "classes": {
      "tree": { ... },
    "enums": {
      "speciesEnum": { ... }
    }
  }
}
----
====

[#metadata-referenceimplementation-schema-class]
=== Class

_Defined in 
ifdef::env-github[]
link:https://github.com/CesiumGS/3d-tiles/tree/main/specification/schema/Schema/class.schema.json[`class.schema.json`]._
endif::[]
ifndef::env-github[]
<<reference-schema-class,`class.schema.json`>>._
endif::[]

A class is a template for metadata entities. Classes provide a list of property definitions. Every entity shall be associated with a class, and the entity's properties shall conform to the class's property definitions. Entities whose properties conform to a class are considered instances of that class.

Classes are defined as entries in the `schema.classes` dictionary, indexed by class ID. Class IDs shall be xref:{url-specification-metadata}README.adoc#metadata-identifiers[identifiers] as defined in the 3D Metadata Specification.

[NOTE]
.Example
====
A "Tree" class, which might describe a table of tree measurements taken in a park. Property definitions are abbreviated here, and introduced in the next section.

[%unnumbered]
[source,json]
----
{
  "schema": {
    "classes": {
      "tree": {
        "name": "Tree",
        "description": "Woody, perennial plant.",
        "properties": {
          "species": { ... },
          "age": { ... },
          "height": { ... },
          "diameter": { ... }
        }
      }
    }
  }
}
----
====

[#metadata-referenceimplementation-schema-class-property]
=== Class Property

_Defined in 
ifdef::env-github[]
link:https://github.com/CesiumGS/3d-tiles/tree/main/specification/schema/Schema/class.property.schema.json[`class.property.schema.json`]._
endif::[]
ifndef::env-github[]
<<reference-schema-class-property,`class.property.schema.json`>>._
endif::[]

Class properties are defined abstractly in a class. The class is instantiated with specific values conforming to these properties. Class properties support a rich variety of data types. Details about the supported types can be found in the xref:{url-specification-metadata}README.adoc#metadata-property[3D Metadata Specification].

Class properties are defined as entries in the `class.properties` dictionary, indexed by property ID. Property IDs shall be xref:{url-specification-metadata}README.adoc#metadata-identifiers[identifiers] as defined in the 3D Metadata Specification.

[NOTE]
.Example
====
A "Tree" class, which might describe a table of tree measurements taken in a park. Properties include species, age, height, and diameter of each tree.

[%unnumbered]
[source,json]
----
{
  "schema": {
    "classes": {
      "tree": {
        "name": "Tree",
        "description": "Woody, perennial plant.",
        "properties": {
          "species": {
            "description": "Type of tree.",
            "type": "ENUM",
            "enumType": "speciesEnum",
            "required": true
          },
          "age": {
            "description": "The age of the tree, in years",
            "type": "SCALAR",
            "componentType": "UINT8",
            "required": true
          },
          "height": {
            "description": "Height of tree measured from ground level, in meters.",
            "type": "SCALAR",
            "componentType": "FLOAT32"
          },
          "diameter": {
            "description": "Diameter at trunk base, in meters.",
            "type": "SCALAR",
            "componentType": "FLOAT32"
          }
        }
      }
    }
  }
}
----
====

[#metadata-referenceimplementation-schema-enum]
=== Enum

_Defined in 
ifdef::env-github[]
link:https://github.com/CesiumGS/3d-tiles/tree/main/specification/schema/Schema/enum.schema.json[`enum.schema.json`]._
endif::[]
ifndef::env-github[]
<<reference-schema-enum,`enum.schema.json`>>._
endif::[]

A set of categorical types, defined as `(name, value)` pairs. Enum properties use an enum as their type.

Enums are defined as entries in the `schema.enums` dictionary, indexed by an enum ID. Enum IDs shall be xref:{url-specification-metadata}README.adoc#metadata-identifiers[identifiers] as defined in the 3D Metadata Specification.

[NOTE]
.Example
====
A "Species" enum defining types of trees. An "Unspecified" enum value is optional, but when provided as the `noData` value for a property (see: xref:{url-specification-metadata}README.adoc#metadata-required-properties-no-data-values-and-default-values[3D Metadata - No Data Values]) may be helpful to identify missing data.

[%unnumbered]
[source,json]
----
{
  "schema": {
    "enums": {
      "speciesEnum": {
        "name": "Species",
        "description": "An example enum for tree species.",
        "values": [
          {"name": "Unspecified", "value": 0},
          {"name": "Oak", "value": 1},
          {"name": "Pine", "value": 2},
          {"name": "Maple", "value": 3}
        ]
      }
    }
  }
}
----
====

[#metadata-referenceimplementation-schema-enum-value]
=== Enum Value

_Defined in 
ifdef::env-github[]
link:https://github.com/CesiumGS/3d-tiles/tree/main/specification/schema/Schema/enum.value.schema.json[`enum.value.schema.json`]._
endif::[]
ifndef::env-github[]
<<reference-schema-enum-value,`enum.value.schema.json`>>._
endif::[]


Pairs of `(name, value)` entries representing possible values of an enum property.

Enum values are defined as entries in the `enum.values` array. Duplicate names or duplicate integer values are not allowed.
