= Objects
* <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`BinaryBodyReference`>>
* <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyboolean,`GlobalPropertyBoolean`>>
* <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`GlobalPropertyCartesian3`>>
* <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyinteger,`GlobalPropertyInteger`>>
* <<reference-tileformats-instanced3dmodel-instanced-3d-model-feature-table,`Instanced 3D Model Feature Table`>> (root object)


'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference]
== BinaryBodyReference

An object defining the reference to a section of the binary body of the features table where the property values are stored if not defined directly in the JSON.

.`BinaryBodyReference` Properties
|===
|   |Type|Description|Required

|**byteOffset**
|`integer`
|The offset into the buffer in bytes.
| &#10003; Yes

|**componentType**
|`string`
|The datatype of components in the property. This is defined only if the semantic allows for overriding the implicit component type. These cases are specified in each tile format.
|No

|**extensions**
|<<reference-tileformats-instanced3dmodel-extension,`extension`>>
|Dictionary object with extension-specific objects.
|No

|**extras**
|<<reference-tileformats-instanced3dmodel-extras,`extras`>>
|Application-specific data.
|No

|===

* **Additional properties are allowed.**
* **JSON schema**: <<reference-tileformats-instanced3dmodel-schema-featuretable-definitions-binarybodyreference,`featureTable.schema.json`>>

=== featureTable/definitions/binaryBodyReference.byteOffset

The offset into the buffer in bytes.

* **Type**: `integer`
* **Required**:  &#10003; Yes
* **Minimum**: `&gt;= 0`

=== featureTable/definitions/binaryBodyReference.componentType

The datatype of components in the property. This is defined only if the semantic allows for overriding the implicit component type. These cases are specified in each tile format.

* **Type**: `string`
* **Required**: No
* **Allowed values**:
** `"BYTE"`
** `"UNSIGNED_BYTE"`
** `"SHORT"`
** `"UNSIGNED_SHORT"`
** `"INT"`
** `"UNSIGNED_INT"`
** `"FLOAT"`
** `"DOUBLE"`

=== featureTable/definitions/binaryBodyReference.extensions

Dictionary object with extension-specific objects.

* **Type**: <<reference-tileformats-instanced3dmodel-extension,`extension`>>
* **Required**: No
* **Additional properties are allowed.**
* **Type of each property**: `object`

=== featureTable/definitions/binaryBodyReference.extras

Application-specific data.

* **Type**: <<reference-tileformats-instanced3dmodel-extras,`extras`>>
* **Required**: No




'''
[#reference-tileformats-instanced3dmodel-extension]
== Extension

Dictionary object with extension-specific objects.

* **Additional properties are allowed.**
* **Type of additional properties**: `object`
* **JSON schema**: <<reference-tileformats-instanced3dmodel-schema-extension,`extension.schema.json`>>




'''
[#reference-tileformats-instanced3dmodel-extras]
== Extras

Application-specific data.



'''
[#reference-tileformats-instanced3dmodel-featuretable]
== Feature Table

A set of semantics containing per-tile and per-feature values defining the position and appearance properties for features in a tile.

.`Feature Table` Properties
|===
|   |Type|Description|Required

|**extensions**
|<<reference-tileformats-instanced3dmodel-extension,`extension`>>
|Dictionary object with extension-specific objects.
|No

|**extras**
|<<reference-tileformats-instanced3dmodel-extras,`extras`>>
|Application-specific data.
|No

|===

* **Additional properties are allowed.**
* **Type of additional properties**: `featureTable/definitions/property`
* **JSON schema**: <<reference-tileformats-instanced3dmodel-schema-featuretable,`featureTable.schema.json`>>

=== featureTable.extensions

Dictionary object with extension-specific objects.

* **Type**: <<reference-tileformats-instanced3dmodel-extension,`extension`>>
* **Required**: No
* **Additional properties are allowed.**
* **Type of each property**: `object`

=== featureTable.extras

Application-specific data.

* **Type**: <<reference-tileformats-instanced3dmodel-extras,`extras`>>
* **Required**: No




'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyboolean]
== GlobalPropertyBoolean

An object defining a global boolean property value for all features.



'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3]
== GlobalPropertyCartesian3

An object defining a global 3-component numeric property values for all features.



'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian4]
== GlobalPropertyCartesian4

An object defining a global 4-component numeric property values for all features.



'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyinteger]
== GlobalPropertyInteger

An object defining a global integer property value for all features.



'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertynumber]
== GlobalPropertyNumber

An object defining a global numeric property value for all features.



'''
[#reference-tileformats-instanced3dmodel-instanced-3d-model-feature-table]
== Instanced 3D Model Feature Table

A set of Instanced 3D Model semantics that contains values defining the position and appearance properties for instanced models in a tile.

.`Instanced 3D Model Feature Table` Properties
|===
|   |Type|Description|Required

|**POSITION**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**POSITION_QUANTIZED**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**NORMAL_UP**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**NORMAL_RIGHT**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**NORMAL_UP_OCT32P**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**NORMAL_RIGHT_OCT32P**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**SCALE**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**SCALE_NON_UNIFORM**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**BATCH_ID**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
|A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
|No

|**INSTANCES_LENGTH**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyinteger,`featureTable/definitions/globalPropertyInteger`>>
|A <<reference-tileformats-instanced3dmodel-globalpropertyinteger,`GlobalPropertyInteger`>> object defining an integer property for all features. Details about this property are described in the 3D Tiles specification.
| &#10003; Yes

|**RTC_CENTER**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`featureTable/definitions/globalPropertyCartesian3`>>
|A <<reference-tileformats-instanced3dmodel-globalpropertycartesian3,`GlobalPropertyCartesian3`>> object defining a 3-component numeric property for all features. Details about this property are described in the 3D Tiles specification.
|No

|**QUANTIZED_VOLUME_OFFSET**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`featureTable/definitions/globalPropertyCartesian3`>>
|A <<reference-tileformats-instanced3dmodel-globalpropertycartesian3,`GlobalPropertyCartesian3`>> object defining a 3-component numeric property for all features. Details about this property are described in the 3D Tiles specification.
|No

|**QUANTIZED_VOLUME_SCALE**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`featureTable/definitions/globalPropertyCartesian3`>>
|A <<reference-tileformats-instanced3dmodel-globalpropertycartesian3,`GlobalPropertyCartesian3`>> object defining a 3-component numeric property for all features. Details about this property are described in the 3D Tiles specification.
|No

|**EAST_NORTH_UP**
|<<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyboolean,`featureTable/definitions/globalPropertyBoolean`>>
|A <<reference-tileformats-instanced3dmodel-globalpropertyboolean,`GlobalPropertyBoolean`>> object defining a boolean property for all features. Details about this property are described in the 3D Tiles specification.
|No

|**extensions**
|<<reference-tileformats-instanced3dmodel-extension,`extension`>>
|Dictionary object with extension-specific objects.
|No

|**extras**
|<<reference-tileformats-instanced3dmodel-extras,`extras`>>
|Application-specific data.
|No

|===

* **Additional properties are allowed.**
* **Type of additional properties**: `featureTable/definitions/property`
* **JSON schema**: <<reference-tileformats-instanced3dmodel-schema-instanced-3d-model-feature-table,`i3dm.featureTable.schema.json`>>

=== Instanced 3D Model Feature Table.POSITION

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.POSITION_QUANTIZED

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.NORMAL_UP

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.NORMAL_RIGHT

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.NORMAL_UP_OCT32P

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.NORMAL_RIGHT_OCT32P

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.SCALE

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.SCALE_NON_UNIFORM

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.BATCH_ID

A <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-binarybodyreference,`featureTable/definitions/binaryBodyReference`>>
* **Required**: No

=== Instanced 3D Model Feature Table.INSTANCES_LENGTH

A <<reference-tileformats-instanced3dmodel-globalpropertyinteger,`GlobalPropertyInteger`>> object defining an integer property for all features. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyinteger,`featureTable/definitions/globalPropertyInteger`>>
* **Required**:  &#10003; Yes

=== Instanced 3D Model Feature Table.RTC_CENTER

A <<reference-tileformats-instanced3dmodel-globalpropertycartesian3,`GlobalPropertyCartesian3`>> object defining a 3-component numeric property for all features. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`featureTable/definitions/globalPropertyCartesian3`>>
* **Required**: No

=== Instanced 3D Model Feature Table.QUANTIZED_VOLUME_OFFSET

A <<reference-tileformats-instanced3dmodel-globalpropertycartesian3,`GlobalPropertyCartesian3`>> object defining a 3-component numeric property for all features. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`featureTable/definitions/globalPropertyCartesian3`>>
* **Required**: No

=== Instanced 3D Model Feature Table.QUANTIZED_VOLUME_SCALE

A <<reference-tileformats-instanced3dmodel-globalpropertycartesian3,`GlobalPropertyCartesian3`>> object defining a 3-component numeric property for all features. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertycartesian3,`featureTable/definitions/globalPropertyCartesian3`>>
* **Required**: No

=== Instanced 3D Model Feature Table.EAST_NORTH_UP

A <<reference-tileformats-instanced3dmodel-globalpropertyboolean,`GlobalPropertyBoolean`>> object defining a boolean property for all features. Details about this property are described in the 3D Tiles specification.

* **Type**: <<reference-tileformats-instanced3dmodel-featuretable-definitions-globalpropertyboolean,`featureTable/definitions/globalPropertyBoolean`>>
* **Required**: No

=== Instanced 3D Model Feature Table.extensions

Dictionary object with extension-specific objects.

* **Type**: <<reference-tileformats-instanced3dmodel-extension,`extension`>>
* **Required**: No
* **Additional properties are allowed.**
* **Type of each property**: `object`

=== Instanced 3D Model Feature Table.extras

Application-specific data.

* **Type**: <<reference-tileformats-instanced3dmodel-extras,`extras`>>
* **Required**: No




'''
[#reference-tileformats-instanced3dmodel-featuretable-definitions-property]
== Property

A user-defined property which specifies application-specific metadata in a tile. Values can refer to sections in the binary body with a <<reference-tileformats-instanced3dmodel-binarybodyreference,`BinaryBodyReference`>> object. Global values can be also be defined directly in the JSON.





