:extensions-url: https://github.com/CesiumGS/glTF/blob/3d-tiles-2.0/extensions/2.1/Vendor

== Conformance

Annex A of this document describes the Objects and Properties required to implement 3D Tiles. Conformance is relative to these elements and as partly expressed via the associated 3D Tiles xref:APPENDIX.adoc#json-schema[JSON Schema].

All figures, examples, notes, and background information are informative.

=== Conformance Class: Core

A conforming 3D Tiles 2.0 client or server SHALL implement the core requirements of the specification.

==== Requirement 1: glTF 2.1

A conforming implementation SHALL support the glTF 2.1 specification.

==== Requirement 2: link:{extensions-url}/3DTILES_tileset/README.md[3DTILES_tileset]

A conforming implementation SHALL support the link:{extensions-url}/3DTILES_tileset/README.md[3DTILES_tileset] glTF extension. This extension is required for defining the structure of a 3D Tiles 2.0 tileset.

==== Requirement 3: link:{extensions-url}/EXT_geospatial_crs/README.md[EXT_geospatial_crs] Extension

A conforming implementation SHOULD support the link:{extensions-url}/EXT_geospatial_crs/README.md[EXT_geospatial_crs] glTF extension. This extension is required for specifying the tileset's global coordinate system, typically https://epsg.org/crs_4978/WGS-84.html[EPSG 4978].

==== Requirement 4: link:{extensions-url}/EXT_georeference/README.md[EXT_georeference] Extension

A conforming implementation SHOULD support the link:{extensions-url}/EXT_georeference/README.md[EXT_georeference] glTF extension. This extension allows defining a tileset in a local coordinate system and georeferenced to a specific latitude and longitude.

=== Conformance Class: Implicit Tiling

A conforming 3D Tiles 2.0 client or server SHOULD implement the implicit tiling requirements of the specification.

==== Requirement 1: link:{extensions-url}/3DTILES_implicit_tiling/README.md[3DTILES_implicit_tiling] Extension

A conforming implementation that supports implicit tiling SHALL support the link:{extensions-url}/3DTILES_implicit_tiling/README.md[3DTILES_implicit_tiling] glTF extension. This extension is required for defining the implicit tiling scheme.

==== Requirement 2: link:{extensions-url}/3DTILES_subtree/README.md[3DTILES_subtree] Extension

A conforming implementation that supports implicit tiling SHALL support the link:{extensions-url}/3DTILES_subtree/README.md[3DTILES_subtree] glTF extension. This extension is required for handling availability and metadata in implicit tilesets.

=== Conformance Class: Additional Bounding Volume Types

A conforming 3D Tiles 2.0 client or server MAY implement the additional bounding volume type requirements of the specification.

==== Requirement 1: link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region]

A conforming implementation MAY support the link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region] glTF extension. This extension allows defining an ellipsoid-conforming region as an additional glTF 2.1 shape type.

==== Requirement 2: link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region]

A conforming implementation MAY support the link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region] glTF extension. This extension allows defining an cylinder-conforming region as an additional glTF 2.1 shape type.

==== Requirement 3: link:{extensions-url}/3DTILES_shape_s2/README.md[3DTILES_shape_s2]

A conforming implementation MAY support the link:{extensions-url}/3DTILES_shape_s2/README.md[3DTILES_shape_s2] glTF extension. This extension enables using S2 cells as as additional glTF 2.1 shape type.

=== Conformance Class: Tileset Metadata

A conforming 3D Tiles 2.0 client or server MAY implement the tileset metadata requirements of the specification.

==== Requirement 1: link:https://github.com/CesiumGS/glTF/blob/proposal-EXT_structural_metadata/extensions/2.0/Vendor/EXT_structural_metadata/README.md#ext_structural_metadata[EXT_structural_metadata] Extension

A conforming implementation that supports tileset metadata SHALL support the link:https://github.com/CesiumGS/glTF/blob/proposal-EXT_structural_metadata/extensions/2.0/Vendor/EXT_structural_metadata/README.md#ext_structural_metadata[EXT_structural_metadata] extension. This extension allows associating metadata with tilesets, tiles, and contents within a tileset.

==== Requirement 2: 3D Metadata specification

A conforming implementation that supports tileset metadata SHALL support the xref:Metadata/README.adoc#metadata-3d-metadata-specification[3D Metadata specification]. This specification defines a standard format for structured metadata in 3D content.

=== Conformance Class: Declarative Styling

A conforming 3D Tiles 2.0 client or server MAY implement the declarative styling requirements of the specification.

==== Requirement 1: 3D Tiles styling

A conforming implementation that supports declarative styling SHALL support the xref:Styling/README.adoc#styling-styling[3D Tiles styles specification]. This specification provides concise declarative styling of tileset features.

=== Conformance Class: Vector Tiles Content Type

A conforming 3D Tiles 2.0 client or server MAY implement the vector tiles content type requirements of the specification.

==== Requirement 1: link:{extensions-url}/3DTILES_tileset_vectors[3DTILES_tileset_vectors]

A conforming implementation that supports the vector tile contents SHALL support the link:{extensions-url}/3DTILES_tileset_vectors[3DTILES_tileset_vectors] glTF extension. This extension allows defining a tileset containing vector data tile contents.

=== Conformance Class: Voxel Tiles Content Type

A conforming 3D Tiles 2.0 client or server MAY implement the voxel tiles content type requirements of the specification.

==== Requirement 1: link:{extensions-url}/3DTILES_tileset_voxels[3DTILES_tileset_voxels]

A conforming implementation that supports voxel tile contents SHALL support the link:{extensions-url}/3DTILES_tileset_voxels[3DTILES_tileset_voxels] glTF extension. This extension allows defining a tileset containing voxel data tile contents.

==== Requirement 2: Implicit Tiling

A conforming implementation that supports voxel tile contents SHALL support the entire Implicit Tiling conformance class.

==== Requirement 3: link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region]

A conforming implementation SHOULD support the link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region] glTF extension. This extension allows defining an ellipsoid-conforming region as an additional glTF 2.1 shape type.

==== Requirement 4: link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region]

A conforming implementation SHOULD support the link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region] glTF extension. This extension allows defining an cylinder-conforming region as an additional glTF 2.1 shape type.

=== Conformance Class: 3D Gaussian Splatting

==== Requirement 1: https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting]

A conforming implementation that supports 3D Gaussian Splatting tile contents SHALL support the https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting] glTF extension. This extension provides a basis for including 3D Gaussian splatting data in glTF.

==== Requirement 2: https://github.com/KhronosGroup/glTF/pull/2531[KHR_gaussian_splatting_compression_spz_2]

A conforming implementation that supports 3D Gaussian Splatting tile contents SHALL support the https://github.com/KhronosGroup/glTF/pull/2531[KHR_gaussian_splatting_compression_spz_2] glTF extension. This extension compresses the 3D Gaussian Splatting data using the SPZ compression format in glTF.
