== Conformance

Annex A of this document contains the link:{gltf-ext-3dtiles_tileset-url}[3DTILES_tileset] glTF 2.1 extension required to implement 3D Tiles.

All figures, examples, notes, and background information are informative.

=== Conformance Class: Core

A conforming 3D Tiles 2.0 client or server *SHALL* implement the core requirements of the specification.

==== Requirement 1: glTF 2.1

A conforming implementation *SHALL* support the glTF 2.1 specification.

==== Requirement 2: link:{gltf-ext-3dtiles_tileset-url}[3DTILES_tileset]

A conforming implementation *SHALL* support the link:{gltf-ext-3dtiles_tileset-url}[3DTILES_tileset] glTF extension.

=== Conformance Class: Coordinate Reference System

A conforming implementation *SHALL* implement the coordinate reference system requirements of the specification.

==== Requirement 1: Support of both Locally-Referenced and Globally-Referenced Tilesets

A conforming implementation *MAY* support both locally-referenced and globally-referenced tilesets.

==== Requirement 2: Support Locally-Referenced Tilesets

A conforming locally-referenced tileset *SHALL* support use of a local coordinate reference system. Tilesets using a local coordinate reference system *SHALL NOT* use the link:{gltf-ext-ext_geospatial_crs-url}[EXT_geospatial_crs] or link:{gltf-ext-ext_georeference-url}[EXT_georeference] glTF Extensions.

==== Requirement 3: Support Globally-Referenced Tilesets 

A conforming globally-referenced tileset *SHOULD* support use of a global coordinate reference system. Tilesets using a global coordinate reference system *SHALL* use the link:{gltf-ext-ext_geospatial_crs-url}[EXT_geospatial_crs] glTF Extension.

=== Conformance Class: Implicit Tiling

A conforming implementation *SHOULD* implement the implicit tiling requirements of the specification.

==== Requirement 1: Support link:{gltf-ext-3dtiles_implicit_tiling-url}[3DTILES_implicit_tiling]

A conforming implementation that supports implicit tiling *SHALL* support the link:{gltf-ext-3dtiles_implicit_tiling-url}[3DTILES_implicit_tiling] glTF extension.

==== Requirement 2: Support link:{gltf-ext-3dtiles_subtree-url}[3DTILES_subtree]

A conforming implementation that supports implicit tiling *SHALL* support the link:{gltf-ext-3dtiles_subtree-url}[3DTILES_subtree] glTF extension.

=== Conformance Class: 3D Gaussian Splatting Tiles Content Type

A conforming implementation *MAY* implement the 3D Gaussian Splatting tiles content type requirements of the specification.

==== Requirement 1: Support link:{gltf-ext-khr_gaussian_splatting-url}[KHR_gaussian_splatting]

A conforming implementation that supports 3D Gaussian Splatting tile content type *SHALL* support the link:{gltf-ext-khr_gaussian_splatting-url}[KHR_gaussian_splatting] glTF extension.

==== Requirement 2: Support link:{gltf-ext-khr_gaussian_splatting_compression_spz_2-url}[KHR_gaussian_splatting_compression_spz_2]

A conforming implementation that supports the 3D Gaussian Splatting tile content type *SHALL* support the link:{gltf-ext-khr_gaussian_splatting_compression_spz_2-url}[KHR_gaussian_splatting_compression_spz_2] glTF extension.

=== Conformance Class: Architecture, Engineering, and Construction Content Type

A conforming implementation *MAY* implement the Architecture, Engineering, and Construction content type requirements of the specification.

==== Requirement 1: Support link:{gltf-ext-khr_mesh_primitive_restart-url}[KHR_mesh_primitive_restart]

A conforming implementation that supports the Architecture, Engineering, and Construction content type *MAY* support the link:{gltf-ext-khr_mesh_primitive_restart-url}[KHR_mesh_primitive_restart] glTF extension.

==== Requirement 2: Support link:{gltf-ext-ext_mesh_primitive_edge_visibility-url}[EXT_mesh_primitive_edge_visibility]

A conforming implementation that supports the Architecture, Engineering, and Construction content type *MAY* support the link:{gltf-ext-ext_mesh_primitive_edge_visibility-url}[EXT_mesh_primitive_edge_visibility] glTF extension.

==== Requirement 3: Support link:{gltf-ext-ext_textureInfo_constant_lod-url}[EXT_textureInfo_constant_lod]

A conforming implementation that supports the Architecture, Engineering, and Construction content type *MAY* support the link:{gltf-ext-ext_textureInfo_constant_lod-url}[EXT_textureInfo_constant_lod] glTF extension.

==== Requirement 4: Support link:{gltf-ext-bentley_materials_line_style-url}[BENTLEY_materials_line_style]

A conforming implementation that supports the Architecture, Engineering, and Construction content type *MAY* support the link:{gltf-ext-bentley_materials_line_style-url}[BENTLEY_materials_line_style] glTF extension.

==== Requirement 5: Support link:{gltf-ext-bentley_materials_point_style-url}[BENTLEY_materials_point_style]

A conforming implementation that supports the Architecture, Engineering, and Construction content type *MAY* support the link:{gltf-ext-bentley_materials_point_style-url}[BENTLEY_materials_point_style] glTF extension.

==== Requirement 6: Support link:{gltf-ext-bentley_materials_planar_fill-url}[BENTLEY_materials_planar_fill]

A conforming implementation that supports the Architecture, Engineering, and Construction content type *MAY* support the link:{gltf-ext-bentley_materials_planar_fill-url}[BENTLEY_materials_planar_fill] glTF extension.

=== Conformance Class: Time-dynamic Tiles Content Type

A conforming implementation *MAY* implement the vector tiles content type requirements of the specification.

==== Requirement 1: Support link:{gltf-ext-khr_node_visibility-url}[KHR_node_visibility]

A conforming implementation that supports the time-dynamic tile content type *SHALL* support the link:{gltf-ext-khr_node_visibility-url}[KHR_node_visibility] glTF extension.

==== Requirement 2: Support link:{gltf-ext-ext_node_visibility_conditions-url}[EXT_node_visibility_conditions]

A conforming implementation that supports the time-dynamic tile content type *SHALL* support the link:{gltf-ext-ext_node_visibility_conditions-url}[EXT_node_visibility_conditions] glTF extension.

=== Conformance Class: Vector Tiles Content Type

A conforming implementation *MAY* implement the vector tiles content type requirements of the specification.

==== Requirement 1: Support link:{gltf-ext-3dtiles_tileset_vectors-url}[3DTILES_tileset_vectors]

A conforming implementation that supports the vector tile content type *SHALL* support the link:{gltf-ext-3dtiles_tileset_vectors-url}[3DTILES_tileset_vectors] glTF extension.

==== Requirement 2: Support link:{gltf-ext-khr_mesh_primitive_restart-url}[KHR_mesh_primitive_restart]

A conforming implementation that supports the vector tile content type *SHALL* support the link:{gltf-ext-khr_mesh_primitive_restart-url}[KHR_mesh_primitive_restart] glTF extension.

==== Requirement 3: Support link:{gltf-ext-ext_mesh_polygon-url}[EXT_mesh_polygon]

A conforming implementation that supports the vector tile content type *SHOULD* support the link:{gltf-ext-ext_mesh_polygon-url}[EXT_mesh_polygon] glTF extension.

==== Requirement 4: Support link:{gltf-ext-3dtiles_layers-url}[3DTILES_layers]

A conforming implementation that supports the vector tile content type *MAY* support the link:{gltf-ext-3dtiles_layers-url}[3DTILES_layers] glTF extension.

=== Conformance Class: Voxel Tiles Content Type

A conforming implementation *MAY* implement the voxel tiles content type requirements of the specification.

==== Requirement 1: Support link:{gltf-ext-3dtiles_implicit_tiling-url}[3DTILES_implicit_tiling]

A conforming implementation that supports voxel tile content type *SHALL* support the link:{gltf-ext-3dtiles_implicit_tiling-url}[3DTILES_implicit_tiling] glTF extension.

==== Requirement 2: Support link:{gltf-ext-3dtiles_subtree-url}[3DTILES_subtree]

A conforming implementation that supports voxel tile content type *SHALL* support the link:{gltf-ext-3dtiles_subtree-url}[3DTILES_subtree] glTF extension.

==== Requirement 3: Support link:{gltf-ext-3dtiles_tileset_voxels-url}[3DTILES_tileset_voxels]

A conforming implementation that supports voxel tile content type *SHALL* support the link:{gltf-ext-3dtiles_tileset_voxels-url}[3DTILES_tileset_voxels] glTF extension.

==== Requirement 4: Support link:{gltf-ext-ext_voxels-url}[EXT_voxels]

A conforming implementation that supports voxel tile content type *SHALL* support the link:{gltf-ext-ext_voxels-url}[EXT_voxels] glTF extension.

==== Requirement 5: Support link:{gltf-ext-3dtiles_shape_ellipsoid_region-url}[3DTILES_shape_ellipsoid_region]

A conforming implementation that supports voxel tile content type *SHOULD* support the link:{gltf-ext-3dtiles_shape_ellipsoid_region-url}[3DTILES_shape_ellipsoid_region] glTF extension.

==== Requirement 6: Support link:{gltf-ext-3dtiles_shape_cylinder_region-url}[3DTILES_shape_cylinder_region]

A conforming implementation that supports voxel tile content type *SHOULD* support the link:{gltf-ext-3dtiles_shape_cylinder_region-url}[3DTILES_shape_cylinder_region] glTF extension.
