:extensions-url: https://github.com/CesiumGS/glTF/blob/3d-tiles-2.0/extensions/2.1/Vendor

[#gltf-extensions-for-3dtiles]
= glTF Extensions for 3D Tiles

[#gltf-tileset-extensions]
== Tileset Extensions

As a 3D Tiles tileset must be a valid glTF 2.1 asset, any extension or extension compatible with glTF 2.1 may be used with 3D Tiles 2.0. There are some specific extensions that are normatively defined by 3D Tiles 2.0. These extensions use the `3DTILES_` prefix to differentiate them.

[#gltf-base-extension]
=== Base Extension

The link:{extensions-url}/3DTILES_tileset/README.md#3dtiles_tileset[3DTILES_tileset] extension specifies a well defined subset of glTF 2.1 for representing a tileset in https://github.com/CesiumGS/3d-tiles/tree/main/specification/[3D Tiles]. It extends the node hierarchy to support Hierarchical Level of Detail (HLOD) for streaming massive 3D scenes. Additionally, it depends on core glTF 2.1 features like external assets and bounding volumes.

[#gltf-supporting-extensions]
=== Supporting Extensions

These tileset extensions are optional supporting extensions that bring features such as implicit tiling, coordinate referencing, and other features to 3D Tiles 2.0 tilesets.

[#gltf-supporting-extensions-implicit-tiling]
==== Implicit Tiling

Implicit tiling defines a concise representation of quadtrees and octrees in 3D Tiles. This regular pattern allows for random access of tiles based on their tile coordinates which enables accelerated spatial queries, new traversal algorithms, and efficient updates of tile content, among other use cases. The link:{extensions-url}/3DTILES_implicit_tiling/README.md#3dtiles_implicit_tiling[3DTILES_implicit_tiling] extension enables implicit tiling workflows in 3D Tiles 2.0.

The link:{extensions-url}/3DTILES_subtree/README.md#3dtiles_subtree[3DTILES_subtree] extension specifies a well defined subset of glTF 2.1 for representing a subtree in 3DTILES_implicit_tiling. A subtree stores tile, content, and child subtree availability, as well as metadata for available tiles and contents.

[#gltf-external-tilesets]
==== External Tilesets

The link:{extensions-url}/3DTILES_external_tileset/README.md#3dtiles_external_tileset[3DTILES_external_tileset] extension allows a tileset to reference external tilesets (other assets with the link:{extensions-url}/3DTILES_tileset/README.md#3dtiles_tileset[3DTILES_tileset] extension). This enables, for example, storing each city in a tileset and then having a global tileset of tilesets. It is also helpful for partitioning large tilesets into multiple smaller tilesets to improve initial load time.

[#gltf-supporting-extensions-coordinate-referencing]
==== Coordinate Referencing

The link:{extensions-url}/3DTILES_crs_geocentric/README.md#3dtiles_crs_geocentric[3DTILES_crs_geocentric] extension indicates that the glTF is in a geocentric coordinate system such as a WGS 84 Earth-centered, Earth-fixed (ECEF) reference frame (EPSG 4978).

The link:{extensions-url}/3DTILES_crs_georeference/README.md#3dtiles_crs_georeference[3DTILES_crs_georeference] extension allows defining a tileset in a local coordinate system and georeferenced to a specific latitude and longitude.

==== Additional Bounding Volume Shapes

Several extensions exist that extend the bounding volumes shapes that can be used with 3D Tiles 2.0. The link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md#3dtiles_shape_ellipsoid_region[3DTILES_shape_ellipsoid_region] extension defines an ellipsoid-conforming region as an additional shape type. Ellipsoid regions are commonly used in geospatial applications to describe volumes that conform to the curvature of the Earth, or other bodies.

The link:{extensions-url}/3DTILES_shape_cylinder_region/README.md#3dtiles_shape_cylinder_region[3DTILES_shape_cylinder_region] extension defines a cylinder-conforming region as an additional shape type. Cylindrical regions are useful for visualizing real-world data that has been captured by cylindrical sensors.

Additionally, the link:{extensions-url}/3DTILES_bounding_volume_S2/README.md#3dtiles_bounding_volume_s2[3DTILES_bounding_volume_S2] extension to 3D Tiles enables using S2 cells as bounding volumes. Due to the properties of S2 described above, this extension is well suited for tilesets that span the whole globe. 

S2 is a geometry library that defines a framework for decomposing the unit sphere into a hierarchy of cells. A cell is a quadrilateral bounded by four geodesics. The S2 cell hierarchy has 6 root cells, that are obtained by projecting the six faces of a cube onto the unit sphere.

Typically, traditional GIS libraries rely on projecting map data from an ellipsoid onto a plane. For example, the Mercator projection is a cylindrical projection, where the ellipsoid is mapped onto a cylinder that is then unrolled as a plane. This method leads to increasingly large distortion in areas as you move further away from the equator. S2 makes it possible to split the Earth into tiles that have no singularities, have relatively low distortion and are nearly equal in size.

[#gltf-content-extensions]
== Content Extensions

Since 3D Tiles 2.0 tilesets are valid glTF 2.1 files, any glTF extension compatible with glTF 2.1 can be used to extend 3D Tiles 2.0. Many core content features of 3D Tiles 2.0 are powered entirely by glTF extensions. Supporting certain types of content means supporting these glTF extensions. This is not an exhaustive list--other extensions may exist within the glTF community that could be used within 3D Tiles 2.0.

[#gltf-content-extensions-aec-rendering]
=== Architectural, Engineering, and Construction Rendering

3D Tiles 2.0 supports edge rendering for AEC workflows through the glTF extensions https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart] and https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_primitive_edge_visibility[EXT_mesh_primitive_edge_visibility]. Implementations for AEC workflows may recognize both extensions in tile content and can either render the content according to the extension definitions or report the extension as unsupported in accordance with glTF 2.1. 

For the styling of points and lines in CAD content, 3D Tiles 2.0 supports the https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_line_style[BENTLEY_materials_line_style] and https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_point_style[BENTLEY_materials_point_style] glTF extensions. These extensions define the properties used to represent hidden and conceptual elements common in civil and engineering rendering workflows. 

Implementations may use https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/EXT_textureInfo_constant_lod[EXT_textureInfo_constant_lod] to maintain consistent texture pattern scale across zoom levels. Implementations may also use https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_planar_fill[BENTLEY_materials_planar_fill] to mitigate z-fighting between co-located surfaces such as labels, roads, and overlapping infrastructure. 

See these glTF extension definitions for details:

 * https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_primitive_edge_visibility[EXT_mesh_primitive_edge_visibility]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_line_style[BENTLEY_materials_line_style]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_point_style[BENTLEY_materials_point_style]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/EXT_textureInfo_constant_lod[EXT_textureInfo_constant_lod]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_planar_fill[BENTLEY_materials_planar_fill]

[#gltf-content-extensions-time-dynamic-content]
=== Time-dynamic Content 

Using the https://github.com/CesiumGS/3d-tiles/tree/3DTILES_dynamic/extensions/3DTILES_content_conditional[3DTILES_content_conditional] extension, implementations may support time-dynamic 3D tiles, enabling multiple representations of the same spatial region within a single tileset (for example, temporal states of terrain, design-model revisions, or alternative geometries such as point clouds and meshes). 

Any tile may be tagged with one or more attribute key/value pairs. Tilesets are not required to tag every tile; untagged tiles are treated as unconditional. Clients select tile content by evaluating these tags against a selection expression supplied at runtime. Where no selection expression is supplied, clients can render the default content declared by the tileset author. 

Authoring tools may use time-dynamic 3D tiles to publish incremental updates without rewriting an entire tileset. 

See the https://github.com/CesiumGS/3d-tiles/tree/3DTILES_dynamic/extensions/3DTILES_content_conditional[3DTILES_content_conditional] for details.

[#gltf-content-extensions-vector-tiles]
=== Vector Tiles

3D Tiles 2.0 supports both 2D and 3D vector data using a 3D-native data model consistent with the rest of the standard and with glTF 2.1. Relevant dependencies include https://github.com/CesiumGS/3d-tiles/blob/donmccurdy/3DTILES_content_gltf_vector/extensions/3DTILES_content_gltf_vector/README.md[3DTILES_content_gltf_vector], https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart] and https://github.com/CesiumGS/glTF/blob/donmccurdy/EXT_mesh_polygon/extensions/2.0/Vendor/EXT_mesh_polygon/README.md[EXT_mesh_polygon]. Tilesets can represent road centerlines, building footprints, large-scale map features, and AEC design linework as vector data. Payloads may be uncompressed or compressed using the https://github.com/CesiumGS/glTF/blob/donmccurdy/EXT_mesh_polygon/extensions/2.0/Vendor/EXT_mesh_polygon/README.md[KHR_meshopt_compression] extension.

3D Tiles 2.0 is designed for efficient transmission and rendering of 3D vector data, which differentiates it from established vector formats like Mapbox Vector Tiles and GeoJSON. Implementations may provide interoperability paths to and from those formats where appropriate. Styling of vector content uses the same declarative styling language defined for other 3D Tiles content types. 

See these glTF extension definitions for details:

 * https://github.com/CesiumGS/3d-tiles/blob/donmccurdy/3DTILES_content_gltf_vector/extensions/3DTILES_content_gltf_vector/README.md[3DTILES_content_gltf_vector]
 * https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart]
 * https://github.com/CesiumGS/glTF/blob/donmccurdy/EXT_mesh_polygon/extensions/2.0/Vendor/EXT_mesh_polygon/README.md[EXT_mesh_polygon]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression]

[#gltf-content-extensions-voxels]
=== Voxels

3D Tiles 2.0 supports voxel volumetric datasets. Conforming voxel tilesets may use the https://github.com/CesiumGS/glTF/tree/primitive-voxels/extensions/2.0/Vendor/EXT_primitive_voxels[EXT_primitive_voxels], the https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_ellipsoid_region], and the https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_cylinder_region] glTF 2.1 extensions in combination with the implicit tiling mechanism defined in 3D Tiles 2.0. 

Both dense and sparse voxel volumes can be supported. Voxel payloads may be uncompressed, or may be compressed using gzip, the glTF https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression[EXT_meshopt_compression] extension, the glTF https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression] extension, or a combination of the available methods.

See these glTF extension definitions for details:

 * https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_ellipsoid_region]
 * https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_cylinder_region]
 * https://github.com/CesiumGS/glTF/tree/primitive-voxels/extensions/2.0/Vendor/EXT_primitive_voxels[EXT_primitive_voxels]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression[EXT_meshopt_compression]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression]

[#gltf-content-extensions-3d-gaussian-splatting]
=== 3D Gaussian Splatting

3D Tiles 2.0 supports 3D Gaussian Splatting content via the https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting] glTF extension. Implementations supporting https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting] should also support https://github.com/CesiumGS/glTF/tree/draft-splat-spz-split/extensions/2.0/Khronos/KHR_gaussian_splatting_compression_spz_2[KHR_gaussian_splatting_compression_spz_2], which defines compression of splat data using the SPZ format. Uncompressed splat content may be used where compression is not required. 3D Gaussian splatting tilesets are compatible with the hierarchical level-of-detail mechanism of 3D Tiles, such that clients may stream and cull splat content using the same traversal rules as other tile content types. 

See these glTF Extension definitions for details:

 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting]
 * https://github.com/CesiumGS/glTF/tree/draft-splat-spz-split/extensions/2.0/Khronos/KHR_gaussian_splatting_compression_spz_2[KHR_gaussian_splatting_compression_spz_2]
