:extensions-url: https://github.com/CesiumGS/glTF/blob/3d-tiles-2.0/extensions/2.1/Vendor
:cesium-gltf-extensions-url: https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor
:khronos-gltf-extensions-url: https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos

[#gltf-extensions-for-3dtiles]
= glTF Extensions for 3D Tiles

[#gltf-tileset-extensions]
== Tileset Extensions

As a 3D Tiles tileset must be a valid glTF 2.1 asset, any extension compatible with glTF 2.1 may be used with 3D Tiles 2.0. There are some specific extensions that are normatively defined by 3D Tiles 2.0. These extensions use the `3DTILES_` prefix to differentiate them.

[#gltf-core-extension]
=== Core Extension

The link:{extensions-url}/3DTILES_tileset/README.md[3DTILES_tileset] extension specifies a well defined subset of glTF 2.1 for representing a tileset in https://github.com/CesiumGS/3d-tiles/tree/main/specification/[3D Tiles]. It extends the node hierarchy to support Hierarchical Level of Detail (HLOD) for streaming massive 3D scenes. Additionally, it depends on core glTF 2.1 features like external assets and bounding volumes.

These concepts are normatively defined within the https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor/3DTILES_tileset[3DTILES_tileset] glTF extension.

* Tilesets, Tiles, and Tile Content
* Geometric Error
* Refinement (Replacement and Additive)
* Bounding Volumes
* Spatial Coherence and Spatial Data Structures
* Implicit Tiling
* External Tilesets
* Coordinate Reference Systems
* Metadata
* Declarative Styling

[#gltf-supporting-extensions]
=== Supporting Extensions

These tileset extensions are optional supporting extensions that bring features such as implicit tiling, coordinate referencing, and other features to 3D Tiles 2.0 tilesets.

[#gltf-supporting-extensions-coordinate-reference-system]
==== Coordinate Reference System

The link:{extensions-url}/EXT_geospatial_crs/README.md[EXT_geospatial_crs] extension indicates that the glTF is in a planetocentric coordinate reference system such as a WGS84 Earth-centered, Earth-fixed (ECEF) geocentric reference frame (EPSG 4978). This can be further configured through either the link:{extensions-url}/EXT_geospatial_crs_wkt2/README.md[EXT_geospatial_crs_wkt2] or link:{extensions-url}/EXT_geospatial_crs_wkid/README.md[EXT_geospatial_crs_wkid] extensions. link:{extensions-url}/EXT_geospatial_crs_wkt2/README.md[EXT_geospatial_crs_wkt2] allows specifying a Well-Known Text (Version 2) string as the coordinate reference system, and link:{extensions-url}/EXT_geospatial_crs_wkid/README.md[EXT_geospatial_crs_wkid] allows specifying a Well-Known ID, such as an ESPG code, as the coordinate reference system.

See the extensions for full normative specification and further examples:

 * link:{extensions-url}/EXT_geospatial_crs/README.md[EXT_geospatial_crs]
 * link:{extensions-url}/EXT_geospatial_crs_wkt2/README.md[EXT_geospatial_crs_wkt2]
 * link:{extensions-url}/EXT_geospatial_crs_wkid/README.md[EXT_geospatial_crs_wkid]

The link:{extensions-url}/EXT_georeference/README.md[EXT_georeference] extension allows defining a tileset in a local coordinate system and georeferenced to a specific latitude and longitude. This extension uses WGS84 by default, but can use link:{extensions-url}/EXT_geospatial_crs/README.md[EXT_geospatial_crs] to specify a different coordinate reference system. See the link:{extensions-url}/EXT_georeference/README.md[EXT_georeference] extension for a full normative specification.

[#gltf-supporting-extensions-implicit-tiling]
==== Implicit Tiling

Implicit tiling defines a concise representation of quadtrees and octrees in 3D Tiles. This regular pattern allows for random access of tiles based on their tile coordinates which enables accelerated spatial queries, new traversal algorithms, and efficient updates of tile content, among other use cases. The link:{extensions-url}/3DTILES_implicit_tiling/README.md[3DTILES_implicit_tiling] extension enables implicit tiling workflows in 3D Tiles 2.0.

The link:{extensions-url}/3DTILES_subtree/README.md[3DTILES_subtree] extension specifies a well defined subset of glTF 2.1 for representing a subtree in 3DTILES_implicit_tiling. A subtree stores tile, content, and child subtree availability, as well as metadata for available tiles and contents.

==== Additional Bounding Volume Shapes

Several extensions exist that extend the bounding volumes shapes that can be used with 3D Tiles 2.0. The link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region] extension defines an ellipsoid-conforming region as an additional shape type. Ellipsoid regions are commonly used in geospatial applications to describe volumes that conform to the curvature of the Earth, or other bodies.

The link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region] extension defines a cylinder-conforming region as an additional shape type. Cylindrical regions are useful for visualizing real-world data that has been captured by cylindrical sensors.

Additionally, the link:{extensions-url}/3DTILES_shape_s2/README.md[3DTILES_shape_s2] extension to 3D Tiles enables using S2 cells as an additional shape type for global near equal-area coverage.

==== Tileset Metadata

The link:{extensions-url}/EXT_structural_metadata/README.md[EXT_structural_metadata] extension allows assigning metadata to tileset, tile, content, vertices, texels, and features in a glTF asset. Use of this extension in 3D Tiles is covered in detail in the xref:Metadata/README.adoc#metadata-3d-metadata-specification[3D Metadata specification].

==== Layers

Layers are a common concept when working with geospatial data, representing semantic or functional groups of geometries requiring common handling by the application. The link:{extensions-url}/3DTILES_layers/README.md[3DTILES_layers] extension adds support for layers. This can be useful for a variety of applications including vector data. See the link:{extensions-url}/3DTILES_layers/README.md[3DTILES_layers] extension specification for further details.

==== Horizon Occlusion Point

To allow for fast horizon culling at runtime, the link:{extensions-url}/3DTILES_horizon_occlusion_point/README.md[3DTILES_horizon_occlusion_point] extension can be used to set a precomputed horizon occlusion point to a tile or contents. This uses a WGS84 ellipsoid by default but can be configured using the link:{extensions-url}/EXT_geospatial_crs/README.md[EXT_geospatial_crs] extension. See the link:{extensions-url}/3DTILES_horizon_occlusion_point/README.md[3DTILES_horizon_occlusion_point] extension specification for further details.

==== Visibility Bounding Volumes

Visibility bounding volumes allow specifying a space where specialized geometry is only visible when a camera is present. The link:{extensions-url}/EXT_node_visibility_volume[EXT_node_visibility_volume] extension allows specifying a bounding volume where an associated node containing a link:{khronos-gltf-extensions-url}/2.0/Khronos/EXT_node_visibility/README.md[EXT_node_visibility] definition is set to become visible. See the link:{extensions-url}/EXT_node_visibility_volume[EXT_node_visibility_volume] extension specification for further details.

[#gltf-content-extensions]
== Content Extensions

Any glTF extension compatible with glTF 2.1 can be used to extend content files. Many core content features of 3D Tiles 2.0 are powered entirely by glTF extensions. Supporting certain types of content means supporting these glTF extensions. This is not an exhaustive list--other extensions may exist within the glTF community that could be used within 3D Tiles 2.0.

[#gltf-content-extensions-3d-gaussian-splatting]
=== 3D Gaussian Splatting

3D Tiles 2.0 supports 3D Gaussian Splatting content via the link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting] glTF extension. Implementations supporting link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting] should also support https://github.com/CesiumGS/glTF/tree/draft-splat-spz-split/extensions/2.0/Khronos/KHR_gaussian_splatting_compression_spz_2[KHR_gaussian_splatting_compression_spz_2], which defines compression of splat data using the SPZ format. Uncompressed splat content may be used where compression is not required. 3D Gaussian splatting tilesets are compatible with the hierarchical level-of-detail mechanism of 3D Tiles, such that clients may stream and cull splat content using the same traversal rules as other tile content types. 

See these glTF Extension definitions for details:

 * link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_gaussian_splatting[KHR_gaussian_splatting]
 * https://github.com/CesiumGS/glTF/tree/draft-splat-spz-split/extensions/2.0/Khronos/KHR_gaussian_splatting_compression_spz_2[KHR_gaussian_splatting_compression_spz_2]

[#gltf-content-extensions-aec-rendering]
=== Architectural, Engineering, and Construction Rendering

3D Tiles 2.0 supports edge rendering for AEC workflows through the glTF extensions https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart] and link:{khronos-gltf-extensions-url}/2.0/Vendor/EXT_mesh_primitive_edge_visibility[EXT_mesh_primitive_edge_visibility]. Implementations for AEC workflows may recognize both extensions in tile content and can either render the content according to the extension definitions or report the extension as unsupported in accordance with glTF 2.1. 

For the styling of points and lines in CAD content, 3D Tiles 2.0 supports the link:{cesium-gltf-extensions-url}/BENTLEY_materials_line_style[BENTLEY_materials_line_style] and link:{cesium-gltf-extensions-url}/BENTLEY_materials_point_style[BENTLEY_materials_point_style] glTF extensions. These extensions define the properties used to represent hidden and conceptual elements common in civil and engineering rendering workflows. 

Implementations may use link:{cesium-gltf-extensions-url}/EXT_textureInfo_constant_lod[EXT_textureInfo_constant_lod] to maintain consistent texture pattern scale across zoom levels. Implementations may also use link:{cesium-gltf-extensions-url}/BENTLEY_materials_planar_fill[BENTLEY_materials_planar_fill] to mitigate z-fighting between co-located surfaces such as labels, roads, and overlapping infrastructure. 

See these glTF extensions for details:

 * https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart]
 * link:{khronos-gltf-extensions-url}/2.0/Vendor/EXT_mesh_primitive_edge_visibility[EXT_mesh_primitive_edge_visibility]
 * link:{cesium-gltf-extensions-url}/BENTLEY_materials_line_style[BENTLEY_materials_line_style]
 * link:{cesium-gltf-extensions-url}/BENTLEY_materials_point_style[BENTLEY_materials_point_style]
 * link:{cesium-gltf-extensions-url}/EXT_textureInfo_constant_lod[EXT_textureInfo_constant_lod]
 * link:{cesium-gltf-extensions-url}/BENTLEY_materials_planar_fill[BENTLEY_materials_planar_fill]

[#gltf-content-extensions-time-dynamic-content]
=== Time-dynamic Content 

Using the link:{extensions-url}/EXT_node_visibility_conditions/README.md[EXT_node_visibility_conditions] extension, implementations may support time-dynamic 3D tiles, enabling multiple representations of the same spatial region within a single tileset (for example, temporal states of terrain, design-model revisions, or alternative geometries such as point clouds and meshes). 

This extension builds upon the the link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_node_visibility/README.md[KHR_node_visibility] extension by adding support for visibility conditions. Any tile may be tagged with one or more attribute key/value pairs. Tilesets are not required to tag every tile; untagged tiles are treated as unconditional. Clients select tile content by evaluating these tags against a selection expression supplied at runtime. Where no selection expression is supplied, clients can render the default content declared by the tileset author.

Authoring tools may use time-dynamic 3D tiles to publish incremental updates without rewriting an entire tileset.

See the link:{extensions-url}/EXT_node_visibility_conditions/README.md[EXT_node_visibility_conditions] extension for details.

[#gltf-content-extensions-vector-tiles]
=== Vector Tiles

3D Tiles 2.0 supports both 2D and 3D vector data using a 3D-native data model consistent with the rest of the standard and with glTF 2.1. Relevant dependencies include link:{extensions-url}/3DTILES_tileset_vectors/README.md[3DTILES_tileset_vectors], https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart] and https://github.com/CesiumGS/glTF/blob/donmccurdy/EXT_mesh_polygon/extensions/2.0/Vendor/EXT_mesh_polygon/README.md[EXT_mesh_polygon]. Tilesets can represent road centerlines, building footprints, large-scale map features, and AEC design linework as vector data. Payloads may be uncompressed or compressed using the link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_meshopt_compression/README.md[KHR_meshopt_compression] extension.

3D Tiles 2.0 is designed for efficient transmission and rendering of 3D vector data, which differentiates it from established vector formats like Mapbox Vector Tiles and GeoJSON. Implementations may provide interoperability paths to and from those formats where appropriate. Styling of vector content uses the same declarative styling language defined for other 3D Tiles content types. 

See these glTF extension definitions for details:

 * link:{extensions-url}/3DTILES_tileset_vectors/README.md[3DTILES_tileset_vectors]
 * https://github.com/CesiumGS/glTF/blob/donmccurdy/EXT_mesh_polygon/extensions/2.0/Vendor/EXT_mesh_polygon/README.md[EXT_mesh_polygon]
 * https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart]
 * link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression]

[#gltf-content-extensions-voxels]
=== Voxels

3D Tiles 2.0 supports voxel volumetric datasets. Conforming voxel tilesets may use the link:{extensions-url}/3DTILES_tileset_voxels/README.md[3DTILES_tileset_voxels], link:{extensions-url}/EXT_voxels/README.md[EXT_voxels], link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region], and link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region] glTF 2.1 extensions in combination with the implicit tiling mechanism defined in 3D Tiles 2.0.

Both dense and sparse voxel volumes can be supported. Voxel payloads may be uncompressed, or may be compressed using gzip, the glTF link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression] extension, or a combination of the available methods.

See these glTF extension definitions for details:

 * link:{extensions-url}/3DTILES_tileset_voxels/README.md[3DTILES_tileset_voxels]
 * link:{extensions-url}/EXT_voxels/README.md[EXT_voxels]
 * link:{extensions-url}/3DTILES_shape_cylinder_region/README.md[3DTILES_shape_cylinder_region]
 * link:{extensions-url}/3DTILES_shape_ellipsoid_region/README.md[3DTILES_shape_ellipsoid_region]
 * link:{khronos-gltf-extensions-url}/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression]
