
[#metadata-referenceimplementation-propertytable-property-table-implementation]
= Property Table Implementation

// Definitions of the directory structure to ensure that relative
// links between ADOC files in sibling directories can be resolved.
ifdef::env-github[]
:url-specification: ../../../
:url-specification-implicittiling: {url-specification}ImplicitTiling/
:url-specification-metadata: {url-specification}Metadata/
:url-specification-metadata-referenceimplementation-schema: {url-specification-metadata-referenceimplementation}Schema/
endif::[]
ifndef::env-github[]
:url-specification-implicittiling:
:url-specification-metadata:
:url-specification-metadata-referenceimplementation-schema: {url-specification-metadata-referenceimplementation}Schema/
endif::[]


The xref:{url-specification-metadata}README.adoc#metadata-3d-metadata-specification[3D Metadata Specification] defines schemas as a description of the structure of metadata, and different storage formats for the metadata. One form of storing metadata is that of a link:../../README.md#binary-table-format[Binary Table Format], where the data is stored in a binary representation of a table. Each column of such a table represents one of the properties of a class. Each row represents a single entity conforming to the class. The following is the description of such a binary table format, referred to as *property table*. It is used as the basis for defining the metadata storage in the following implementations:

* xref:{url-specification-implicittiling}README.adoc#implicittiling-timplicit-tiling[3D Tiles Metadata Implicit Tilesets] - Assigns metadata to tilesets, tiles, groups, and contents in a 3D Tiles tileset. A property table is defined for subtrees of an implicit tile hierarchy, and stores metadata that is associated with the nodes of such a subtree.
* https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_structural_metadata[`EXT_structural_metadata`] -- Assigns metadata to vertices, texels, and features in a glTF asset. A property table is defined in the top-level extension object. The property values are stored in standard glTF buffer views.

The full JSON schema definition for this implementation can be found in link:../../../schema/PropertyTable/[the PropertyTable directory of the specification].

[#metadata-referenceimplementation-propertytable-property-tables]
== Property Tables

_Defined in link:https://github.com/CesiumGS/3d-tiles/tree/draft-1.1/specification/schema/PropertyTable/propertyTable.schema.json[propertyTable.schema.json]._

A property table must specify the following elements:

* Its class (`class`), which refers to a class ID in a xref:{url-specification-metadata-referenceimplementation-schema}README.adoc#metadata-referenceimplementation-schema-schema[Schema].
* A dictionary of properties (`properties`), where each entry describes the binary storage of the data for the corresponding class property.
* A count (`count`) for the number of elements (rows) in the property table.

The property table may provide value arrays for only a subset of the properties of its class, but class properties that are marked `required: true` in the schema must not be omitted.

[NOTE]
.Example
====
A `tree_survey_2021-09-29` property table, implementing the `tree` class defined in the xref:{url-specification-metadata-referenceimplementation-schema}README.adoc#metadata-referenceimplementation-schema-schema[Schema] examples. The table contains observations for 10 trees. Details about the class properties will be given in later examples.

[source,json]
----
"schema": { ... },
"propertyTables": [{
  "name": "tree_survey_2021-09-29",
  "class": "tree",
  "count": 10,
  "properties": {
    "species": { ... },
    "age": { ... },
    "height": { ... },
    // "diameter" is not required and has been omitted from this table.
  }
}]
----
====

[#metadata-referenceimplementation-propertytable-property-table-properties]
== Property Table Properties

_Defined in link:https://github.com/CesiumGS/3d-tiles/tree/draft-1.1/specification/schema/PropertyTable/propertyTable.property.schema.json[propertyTable.property.schema.json]._

Each property definition in a property table represents one column of the table. This column data is stored in binary form, using the encoding defined in the xref:{url-specification-metadata}README.adoc#metadata-binary-table-format[Binary Table Format] section of the 3D Metadata Specification. The actual data is stored in a binary buffer, and the property refers to a section of this buffer that is called a _buffer view_.

* In the xref:{url-specification}README.adoc#core-metadata[3D Tiles Metadata] implementation, a buffer view is defined as part of xref:{url-specification-implicittiling}README.adoc#implicittiling-buffers-and-buffer-views[subtrees in implicit tilesets].
* In the link:https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata[`3DTILES_metadata`] extension for 3D Tiles 1.0, a buffer view is defined as part of link:https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling#buffers-and-buffer-views[subtrees the `3DTILES_implicit_tiling` extension].
* In the https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_structural_metadata[`EXT_structural_metadata`], a buffer view is a standard glTF buffer view.

The exact structure of each property entry depends on the xref:{url-specification-metadata}README.adoc#metadata-property[property type]:

* Every property definition must define the `values` that store the raw data of the actual values.
* Properties that have the `STRING` component type must define the `stringOffsets`, as defined in xref:{url-specification-metadata}README.adoc#metadata-strings[Strings].
* Properties that are variable-length arrays must define the `arrayOffsets`, as defined in xref:{url-specification-metadata}README.adoc#metadata-arrays[Arrays].

For variable-length arrays of strings, both the `stringOffsets` and the `arrayOffsets` are required.

[NOTE]
.Example
====
The property table from the previous example, with details about the binary storage of the property values

[source,json]
----
{
  "propertyTables": [{
    "name": "tree_survey_2021-09-29",
    "class": "tree",
    "count": 10,
    "properties": {
      "species": {
        "values": 2,
        "stringOffsets": 3
      },
      "age": {
        "values": 1
      },
      "height": {
        "values": 0
      },
      // "diameter" is not required and has been omitted from this table.
    }
  }]
}
----
====

Each buffer view `byteOffset` must be aligned to a multiple of the size of the xref:{url-specification-metadata}README.adoc#metadata-component-type[`componentType`] of the respective property.

[NOTE]
.Implementation Note
====
Authoring tools may choose to align all buffer views to 8-byte boundaries for consistency, but client implementations should only depend on 8-byte alignment for buffer views containing 64-bit component types.
====

For the `arrayOffsets` and `stringOffsets` buffer views, the property can also define the `arrayOffsetType` and `stringOffsetType`, which describe the
storage type for array- and string offsets, respectively. Allowed types are `UINT8`, `UINT16`, `UINT32`, and `UINT64`. The default is `UINT32`.

A property may override the xref:{url-specification-metadata}README.adoc#metadata-minimum-and-maximum-values[`minimum` and `maximum` values] and the xref:{url-specification-metadata}README.adoc#metadata-offset-and-scale[`offset` and `scale`] from the property definition in the class, to account for the actual range of values that is stored in the property table.
