
[#gltf-gltf-extensions-for-3dtiles]
= glTF Extensions for 3D Tiles

== Extension Definitions

include::3DTILES_tileset/README.adoc[]

include::3DTILES_implicit_tiling/README.adoc[]

include::3DTILES_subtree/README.adoc[]

include::3DTILES_geocentric_crs/README.adoc[]

== Content Extensions

Since 3D Tiles 2.0 tilesets are valid glTF 2.1 files, any extension compatible with glTF 2.1 can be used. Many core content features of 3D Tiles 2.0 are actually powered entirely by glTF extensions. Supporting certain types of content means supporting these glTF extensions.

=== Architectural, Engineering, and Construction Rendering

3D Tiles 2.0 supports edge rendering for AEC workflows through the glTF extensions https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart] and https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_primitive_edge_visibility[EXT_mesh_primitive_edge_visibility]. Implementations for AEC workflows may recognize both extensions in tile content and can either render the content according to the extension definitions or report the extension as unsupported in accordance with glTF 2.1. 

For the styling of points and lines in CAD content, 3D Tiles 2.0 supports the https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_line_style[BENTLEY_materials_line_style] and https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_point_style[BENTLEY_materials_point_style] glTF extensions. These extensions define the properties used to represent hidden and conceptual elements common in civil and engineering rendering workflows. 

Implementations may use https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/EXT_textureInfo_constant_lod[EXT_textureInfo_constant_lod] to maintain consistent texture pattern scale across zoom levels. Implementations may also use https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_planar_fill[BENTLEY_materials_planar_fill] to mitigate z-fighting between co-located surfaces such as labels, roads, and overlapping infrastructure. 

See these glTF extension definitions for details:

 * https://github.com/CesiumGS/glTF/tree/donmccurdy/KHR_mesh_primitive_restart/extensions/2.0/Khronos/KHR_mesh_primitive_restart[KHR_mesh_primitive_restart]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_primitive_edge_visibility[EXT_mesh_primitive_edge_visibility]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_line_style[BENTLEY_materials_line_style]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_point_style[BENTLEY_materials_point_style]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/EXT_textureInfo_constant_lod[EXT_textureInfo_constant_lod]
 * https://github.com/CesiumGS/glTF/tree/vendor-extensions/extensions/2.0/Vendor/BENTLEY_materials_planar_fill[BENTLEY_materials_planar_fill]

=== Time-dynamic Content 

Using the https://github.com/CesiumGS/3d-tiles/tree/3DTILES_dynamic/extensions/3DTILES_content_conditional[3DTILES_content_conditional] extension, implementations may support time-dynamic 3D tiles, enabling multiple representations of the same spatial region within a single tileset (for example, temporal states of terrain, design-model revisions, or alternative geometries such as point clouds and meshes). 

Any tile may be tagged with one or more attribute key/value pairs. Tilesets are not required to tag every tile; untagged tiles are treated as unconditional. Clients select tile content by evaluating these tags against a selection expression supplied at runtime. Where no selection expression is supplied, clients can render the default content declared by the tileset author. 

Authoring tools may use time-dynamic 3D tiles to publish incremental updates without rewriting an entire tileset. 

See the https://github.com/CesiumGS/3d-tiles/tree/3DTILES_dynamic/extensions/3DTILES_content_conditional[3DTILES_content_conditional] for details.

=== Voxels

3D Tiles 2.0 supports voxel volumetric datasets. Conforming voxel tilesets may use the https://github.com/CesiumGS/glTF/tree/primitive-voxels/extensions/2.0/Vendor/EXT_primitive_voxels[EXT_primitive_voxels], the https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_ellipsoid_region], and the https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_cylinder_region] glTF 2.1 extensions in combination with the implicit tiling mechanism defined in 3D Tiles 2.0. 

Both dense and sparse voxel volumes can be supported. Voxel payloads may be uncompressed, or may be compressed using gzip, the glTF https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression[EXT_meshopt_compression] extension, the glTF https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression] extension, or a combination of the available methods.

See these glTF extension definitions for details:

 * https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_ellipsoid_region]
 * https://github.com/CesiumGS/glTF/tree/3d-tiles-2.0/extensions/2.1/Vendor[3DTILES_shape_cylinder_region]
 * https://github.com/CesiumGS/glTF/tree/primitive-voxels/extensions/2.0/Vendor/EXT_primitive_voxels[EXT_primitive_voxels]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression[EXT_meshopt_compression]
 * https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_meshopt_compression[KHR_meshopt_compression]

=== 3D Gaussian Splatting

3D Tiles 2.0 supports 3D Gaussian Splatting content via the `KHR_gaussian_splatting` glTF extension. Implementations supporting `KHR_gaussian_splatting` should also support `KHR_gaussian_splatting_compression_spz_2`, which defines compression of splat data using the SPZ format. Uncompressed splat content may be used where compression is not required. 3D Gaussian splatting tilesets are compatible with the hierarchical level-of-detail mechanism of 3D Tiles, such that clients may stream and cull splat content using the same traversal rules as other tile content types. 
